platform :ios, '8.0'
target 'LocalizableTest' do
    pod 'MBProgressHUD', '~> 0.9.1'
    pod 'MSWeakTimer', '~> 1.1.0'
    pod 'MGSwipeTableCell', '~> 1.5.1'
    pod 'MJRefresh', '~> 2.4.11'
    pod 'IQKeyboardManager'
    pod 'Masonry'
    pod 'SafeKit'
    pod 'UMengSocialCOM'
end
inhibit_all_warnings!